export const VIDEO_ADDED = 'VIDEO_ADDED';
export const VIDEO_DOWNLOAD_STARTED = 'VIDEO_DOWNLOAD_STARTED';
export const VIDEO_DOWNLOAD_PROGRESS = 'VIDEO_DOWNLOAD_PROGRESS';
export const VIDEO_DOWNLOAD_COMPLETE = 'VIDEO_DOWNLOAD_COMPLETE';
