export const DOWNLOAD_VIDEO = 'VIDEO_ACTION_DOWNLOAD_VIDEO';
export const CHANGE_SAVE_FOLDER = 'CONFIG_ACTION_CHANGE_SAVE_FOLDER';
export const MAXIMIZE_WINDOW = 'WINDOW_ACTION_MAXIMIZE_WINDOW';
export const UNMAXIMIZE_WINDOW = 'WINDOW_ACTION_UNMAXIMIZE_WINDOW';
export const MINIMIZE_WINDOW = 'WINDOW_ACTION_MINIMIZE_WINDOW';
export const CLOSE_WINDOW = 'WINDOW_ACTION_CLOSE_WINDOW';

export const VIDEO_ACTION_ADDED = 'VIDEO_ACTION_ADDED';
export const VIDEO_ACTION_METADATA_RECEIVED = 'VIDEO_ACTION_METADATA_RECEIVED';
export const VIDEO_ACTION_DOWNLOAD_STARTED = 'VIDEO_ACTION_DOWNLOAD_STARTED';
export const VIDEO_ACTION_DOWNLOAD_PROGRESS = 'VIDEO_ACTION_DOWNLOAD_PROGRESS';
export const VIDEO_ACTION_DOWNLOAD_COMPLETE = 'VIDEO_ACTION_DOWNLOAD_COMPLETE';
export const VIDEO_ACTION_DOWNLOAD_ERROR = 'VIDEO_ACTION_DOWNLOAD_ERROR';
export const CONFIG_ACTION_SAVE_FOLDER_CHANGED = 'CONFIG_ACTION_SAVE_FOLDER_CHANGED';
export const WINDOW_STATE_CHANGED = 'WINDOW_ACTION_STATE_CHANGED';
