export const DOWNLOAD_VIDEO = 'VIDEO_ACTION_DOWNLOAD_VIDEO';

export const VIDEO_ACTION_ADDED = 'VIDEO_ACTION_ADDED';
export const VIDEO_ACTION_METADATA_RECEIVED = 'VIDEO_ACTION_METADATA_RECEIVED';
export const VIDEO_ACTION_DOWNLOAD_STARTED = 'VIDEO_ACTION_DOWNLOAD_STARTED';
export const VIDEO_ACTION_DOWNLOAD_PROGRESS = 'VIDEO_ACTION_DOWNLOAD_PROGRESS';
export const VIDEO_ACTION_DOWNLOAD_COMPLETE = 'VIDEO_ACTION_DOWNLOAD_COMPLETE';
export const VIDEO_ACTION_DOWNLOAD_ERROR = 'VIDEO_ACTION_DOWNLOAD_ERROR';
