export const SERVER_DO_VIDEO_DOWNLOAD = 'SERVER_DO_VIDEO_DOWNLOAD';
export const SERVER_CHANGE_SAVE_FOLDER = 'SERVER_CHANGE_SAVE_FOLDER';

export const SERVER_VIDEO_ADDED = 'SERVER_VIDEO_ADDED';
export const SERVER_VIDEO_METADATA_RECEIVED = 'SERVER_VIDEO_METADATA_RECEIVED';
export const SERVER_VIDEO_DOWNLOAD_STARTED = 'SERVER_VIDEO_DOWNLOAD_STARTED';
export const SERVER_VIDEO_DOWNLOAD_ERROR = 'SERVER_VIDEO_DOWNLOAD_ERROR';
export const SERVER_VIDEO_DOWNLOAD_PROGRESS = 'SERVER_VIDEO_DOWNLOAD_PROGRESS';
export const SERVER_VIDEO_DOWNLOAD_COMPLETED = 'SERVER_VIDEO_DOWNLOAD_COMPLETED';
export const SERVER_SAVE_FOLDER_CHANGED = 'SERVER_SAVE_FOLDER_CHANGED';
