export const VIDEO_DOWNLOAD = 'VIDEO_DOWNLOAD';
export const VIDEO_DOWNLOAD_STARTED = 'VIDEO_DOWNLOAD_STARTED';
export const VIDEO_DOWNLOAD_PROGRESS = 'VIDEO_DOWNLOAD_PROGRESS';
export const VIDEO_DOWNLOAD_COMPLETED = 'VIDEO_DOWNLOAD_COMPLETED';
