export const VIDEO_DOWNLOAD = 'VIDEO_DOWNLOAD';
export const VIDEO_METADATA_RECEIVED = 'VIDEO_METADATA_RECEIVED';
export const VIDEO_DOWNLOAD_STARTED = 'VIDEO_DOWNLOAD_STARTED';
export const VIDEO_DOWNLOAD_ERROR = 'VIDEO_DOWNLOAD_ERROR';
export const VIDEO_DOWNLOAD_PROGRESS = 'VIDEO_DOWNLOAD_PROGRESS';
export const VIDEO_DOWNLOAD_COMPLETED = 'VIDEO_DOWNLOAD_COMPLETED';
